//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using System.Web;
using System.Collections.Generic;

namespace StrixIT.Platform.Core.Tests
{
    [TestClass]
    public class StrixPlatformTests
    {
        [TestMethod]
        public void PlatformShouldReturnListOfCultures()
        {
            var list = StrixPlatform.Cultures;
            Assert.AreEqual(3, list.Count);
            Assert.IsTrue(list.Any(c => c.Code == "nl" && c.NativeName == "Nederlands"));
        }

        [TestMethod]
        public void PlatformShouldReturnFirstConfiguredCultureAsDefault()
        {
            var result = StrixPlatform.DefaultCultureCode;
            Assert.AreEqual("en", result);
        }
    }
}
