//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using StrixIT.Platform.Core.Environment;
using StrixIT.Platform.Web;

namespace StrixIT.Platform.Core.UnitTests.Resources
{
    [TestClass]
    public class ResourceTests
    {
        #region Public Methods

        [TestMethod]
        public void GetResourcesForEnShouldReturnResourceStringsForEn()
        {
            var controller = GetController("en");
            var result = (ClientResourceCollection)controller.GetResources("tests").Data;
            Assert.AreEqual("User", result["membership"]["user"]);
            Assert.AreEqual("Permission", result["membership"]["permission"]);
            Assert.AreEqual("News", result["cms"]["news"]);
            Assert.AreEqual("Comment", result["cms"]["comment"]);
        }

        [TestMethod]
        public void GetResourcesForNlShouldReturnResourceStringsForNl()
        {
            var controller = GetController("nl");
            var result = (ClientResourceCollection)controller.GetResources("tests").Data;
            Assert.AreEqual("Gebruiker", result["membership"]["user"]);
            Assert.AreEqual("Recht", result["membership"]["permission"]);
            Assert.AreEqual("Nieuws", result["cms"]["news"]);
            Assert.AreEqual("Commentaar", result["cms"]["comment"]);
        }

        #endregion Public Methods

        #region Private Methods

        private HomeController GetController(string currentCultureCode)
        {
            var cultureServiceMock = new Mock<ICultureService>();
            cultureServiceMock.Setup(c => c.CurrentCultureCode).Returns(currentCultureCode);
            var environmentMock = new Mock<IEnvironment>();
            environmentMock.Setup(e => e.Cultures).Returns(cultureServiceMock.Object);
            return new HomeController(environmentMock.Object, new ResourceService(cultureServiceMock.Object));
        }

        #endregion Private Methods
    }
}