//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.VisualStudio.TestTools.UnitTesting;
using StrixIT.Platform.Core;
using System;
using System.Linq;

namespace StrixIT.Platform.Core.Tests
{
    [TestClass()]
    public class FilterSortPageOptionsTest
    {
        [TestMethod()]
        public void ExtractFieldShouldReturnTheFieldAndRemoveItFromTheFilter()
        {
            FilterOptions target = new FilterOptions();
            target.Filter.Filters.Add(new FilterField { Field = "Date", Operator = FilterFieldOperator.Equals, Value = DateTime.Now.ToString() });
            target.Filter.Filters.Add(new FilterField { Field = "Name", Operator = FilterFieldOperator.Contains, Value = "Test" });
            var actual = target.ExtractField("name");
            Assert.AreEqual("Test", actual.Value);
            Assert.AreEqual(1, target.Filter.Filters.Count);
        }
    }
}
