//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using Newtonsoft.Json;
using StrixIT.Platform.Core;
using StrixIT.Platform.Framework.Environment;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StrixIT.Platform.Web.Tests
{
    [TestClass]
    public class SessionTests
    {
        #region Private Fields

        private Mock<HttpContextBase> _httpContextMock = new Mock<HttpContextBase>();
        private Mock<HttpSessionStateBase> _sessionMock = new Mock<HttpSessionStateBase>();

        #endregion Private Fields

        #region Public Methods

        [TestMethod]
        public void GetDictionaryFromSessionWhenStoredInSessionAsSerializedStringShouldReturnTheDictionary()
        {
            var service = GetSessionService();
            var expected = new Dictionary<Guid, string>();
            expected.Add(Guid.NewGuid(), "Main");
            expected.Add(Guid.NewGuid(), "Sub");
            _sessionMock.Setup(s => s["testdictionary"]).Returns(JsonConvert.SerializeObject(expected));
            var result = service.Get<Dictionary<Guid, string>>("testdictionary");
            Assert.IsNotNull(result);
            Assert.AreEqual(expected.First().Key, result.First().Key);
            Assert.AreEqual(expected.Last().Value, result.Last().Value);
        }

        [TestMethod]
        public void GetGuidFromSessionWhenStoredInSessionAsSerializedStringShouldReturnParsedGuid()
        {
            var service = GetSessionService();
            var expected = Guid.NewGuid();
            _sessionMock.Setup(s => s[PlatformConstants.CURRENTGROUPID.ToLower()]).Returns(JsonConvert.SerializeObject(expected));
            var result = service.Get<Guid>(PlatformConstants.CURRENTGROUPID);
            Assert.AreEqual(expected, result);
        }

        [TestMethod]
        public void GetStringFromSessionWhenStoredInSessionAsSerializedStringShouldReturnString()
        {
            var service = GetSessionService();
            var expected = "admin@strixit.com";
            _sessionMock.Setup(s => s[PlatformConstants.CURRENTUSEREMAIL.ToLower()]).Returns(JsonConvert.SerializeObject(expected));
            var result = service.Get<string>(PlatformConstants.CURRENTUSEREMAIL);
            Assert.AreEqual(expected, result);
        }

        #endregion Public Methods

        #region Private Methods

        private SessionService GetSessionService()
        {
            _httpContextMock.Setup(m => m.Session).Returns(_sessionMock.Object);
            return new SessionService(_httpContextMock.Object);
        }

        #endregion Private Methods
    }
}