//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace StrixIT.Platform.Web.Tests
{
    public class CustomValidateEntity : TestEntity
    {
        #region Public Constructors

        static CustomValidateEntity()
        {
            CustomValidateEntity.AddValidationRule<CustomValidateEntity>(x =>
            {
                ValidationResult result = null;

                if (x.Name == null || !x.Name.StartsWith("Test"))
                {
                    result = new ValidationResult(@"Name is invalid because it does not start with ""Test""", new string[] { "Name" });
                }

                return result;
            });
        }

        #endregion Public Constructors
    }
}