//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Web.Mvc;

namespace StrixIT.Platform.Web.Tests
{
    public class TestController : Controller
    {
        #region Public Constructors

        public TestController()
        {
            this.ControllerContext = new ControllerContext();
        }

        #endregion Public Constructors

        #region Public Methods

        public bool TryValidate(object model)
        {
            return this.TryValidateModel(model);
        }

        #endregion Public Methods
    }
}