//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using StrixIT.Platform.Core;
using System;

namespace StrixIT.Platform.Web.Tests
{
    [Serializable]
    public class TestEntity : ValidationBase
    {
        #region Public Properties

        [StrixNotDefault]
        public DateTime? Date { get; set; }

        public string Description { get; set; }
        public int Id { get; set; }

        public bool IsActive { get; set; }
        public string Name { get; set; }

        [StrixRequired]
        public long Number { get; set; }

        public decimal Price { get; set; }
        public double Value { get; set; }

        #endregion Public Properties
    }
}