//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations.Schema;

namespace StrixIT.Platform.Framework.Tests
{
    [ComplexType]
    public class Address
    {
        #region Public Properties

        public string City { get; set; }
        public string Street { get; set; }

        #endregion Public Properties
    }
}