//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using StrixIT.Platform.Core;
using System.Data.Entity;

namespace StrixIT.Platform.Framework.Tests
{
    public class TestDataSource : EntityFrameworkDataSource
    {
        #region Public Constructors

        public TestDataSource()
            : this(new Configuration(), "TestConnection")
        {
        }

        public TestDataSource(string connection)
    : this(new Configuration(), connection)
        {
        }

        public TestDataSource(IConfiguration config, string connection)
            : base(config, connection)
        {
            Database.SetInitializer<TestDataSource>(new TestDataSourceInitializer());
        }

        #endregion Public Constructors

        #region Public Properties

        public DbSet<CompositeKeyEntity> CompositeKeyEntities { get; set; }
        public DbSet<GuidEntity> GuidEntities { get; set; }
        public DbSet<TestEntity> IntEntities { get; set; }

        #endregion Public Properties

        #region Protected Methods

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CompositeKeyEntity>().HasKey(c => new { c.Id, c.Culture, c.VersionNumber });
            modelBuilder.Entity<TestCustomFieldValue>().HasKey(c => new { c.CustomFieldId, c.UserId, c.Culture });
            modelBuilder.Entity<TestEntity>().Ignore(t => t.Description);
            modelBuilder.Entity<CompositeKeyEntity>().HasMany(e => e.Siblings).WithMany(e => e.OtherSiblings);
            base.OnModelCreating(modelBuilder);
        }

        #endregion Protected Methods
    }
}