//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace StrixIT.Platform.Framework.Tests
{
    public class TestCustomFieldValue : CustomFieldValue<TestCustomField>
    {
        #region Public Properties

        public string Culture { get; set; }
        public Guid UserId { get; set; }

        #endregion Public Properties
    }
}