//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace StrixIT.Platform.Framework.Tests
{
    public class TestCustomField : CustomField
    {
        #region Public Properties

        public Guid GroupId { get; set; }

        #endregion Public Properties
    }
}