//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;

namespace StrixIT.Platform.Core.Tests
{
    [TestClass()]
    public class DateTimeExtensionTests
    {
        #region Public Methods

        [TestMethod]
        public void WhenADateTimeIsInRangeTheCheckForRangeShouldReturnTrue()
        {
            var dateTime = DateTime.Now;
            var result = dateTime.IsInRange(DateTime.Now.AddDays(-1), DateTime.Now.AddDays(2));
            Assert.IsTrue(result);
        }

        [TestMethod]
        public void WhenADateTimeIsNotInRangeTheCheckForRangeShouldReturnFalse()
        {
            var dateTime = DateTime.Now;
            var result = dateTime.IsInRange(DateTime.Now.AddDays(-10), DateTime.Now.AddDays(-5));
            Assert.IsFalse(result);
        }

        #endregion Public Methods
    }
}