//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using StrixIT.Platform.Framework.Environment;
using System.Linq;

namespace StrixIT.Platform.Core.Tests
{
    [TestClass]
    public class CultureTests
    {
        #region Public Methods

        [TestMethod]
        public void PlatformShouldReturnFirstConfiguredCultureAsDefault()
        {
            var configMock = new Mock<IConfiguration>();
            var config = new PlatformConfiguration();
            config.Cultures = "en,nl,de";
            configMock.Setup(c => c.GetConfiguration<PlatformConfiguration>()).Returns(config);
            var service = new CultureService(configMock.Object, null);
            var result = service.DefaultCultureCode;
            Assert.AreEqual("en", result);
        }

        [TestMethod]
        public void PlatformShouldReturnListOfCultures()
        {
            var configMock = new Mock<IConfiguration>();
            var config = new PlatformConfiguration();
            config.Cultures = "en,nl,de";
            configMock.Setup(c => c.GetConfiguration<PlatformConfiguration>()).Returns(config);
            var service = new CultureService(configMock.Object, null);
            var list = service.Cultures;
            Assert.AreEqual(3, list.Count);
            Assert.IsTrue(list.Any(c => c.Code == "nl" && c.NativeName == "Nederlands"));
        }

        #endregion Public Methods
    }
}