//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations.Schema;

namespace StrixIT.Platform.Core.Tests
{
    [ComplexType]
    public class Address
    {
        public string Street { get; set; }
        public string City { get; set; }
    }
}