//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace StrixIT.Platform.Core.Tests
{
    public class CompositeKeyEntity
    {
        #region Public Properties

        public string Culture { get; set; }
        public string Data { get; set; }
        public Guid Id { get; set; }
        public PersonalInfo Info { get; set; }
        public ICollection<CompositeKeyEntity> OtherSiblings { get; set; }
        public ICollection<CompositeKeyEntity> Siblings { get; set; }
        public int VersionNumber { get; set; }

        #endregion Public Properties
    }
}