//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace StrixIT.Platform.Core.Tests
{
    public class GuidEntity
    {
        #region Public Properties

        public string Description { get; set; }
        public Guid Id { get; set; }

        public string Name { get; set; }

        #endregion Public Properties
    }
}