//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Data.Entity;

namespace StrixIT.Platform.Core.Tests
{
    public class TestDataSourceInitializer : DropCreateDatabaseAlways<TestDataSource>
    {
        #region Protected Methods

        protected override void Seed(TestDataSource context)
        {
        }

        #endregion Protected Methods
    }
}