//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Data.Entity;

namespace StrixIT.Platform.Core.Tests
{
    public class TestDataSource : EntityFrameworkDataSource
    {
        public DbSet<TestEntity> IntEntities { get; set; }
        public DbSet<GuidEntity> GuidEntities { get; set; }
        public DbSet<CompositeKeyEntity> CompositeKeyEntities { get; set; }

        public TestDataSource()
            : this("TestConnection")
        {
        }

        public TestDataSource(string connection)
            : base(connection)
        {
            Database.SetInitializer<TestDataSource>(new TestDataSourceInitializer());
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CompositeKeyEntity>().HasKey(c => new { c.Id, c.Culture, c.VersionNumber });
            modelBuilder.Entity<TestCustomFieldValue>().HasKey(c => new { c.CustomFieldId, c.UserId, c.Culture });
            modelBuilder.Entity<TestEntity>().Ignore(t => t.Description);
            modelBuilder.Entity<CompositeKeyEntity>().HasMany(e => e.Siblings).WithMany(e => e.OtherSiblings);
            base.OnModelCreating(modelBuilder);
        }
    }
}