//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace StrixIT.Platform.Core.Tests
{
    public class TestCustomFieldValue : CustomFieldValue<TestCustomField>
    {
        public Guid UserId { get; set; }

        public string Culture { get; set; }
    }
}
