//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrixIT.Platform.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Diacritics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Diacritics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StrixIT.Platform.Core.Resources.Diacritics", typeof(Diacritics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string á {
            get {
                return ResourceManager.GetString("á", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string à {
            get {
                return ResourceManager.GetString("à", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string â {
            get {
                return ResourceManager.GetString("â", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string ä {
            get {
                return ResourceManager.GetString("ä", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string ã {
            get {
                return ResourceManager.GetString("ã", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string å {
            get {
                return ResourceManager.GetString("å", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ae.
        /// </summary>
        public static string æ {
            get {
                return ResourceManager.GetString("æ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c.
        /// </summary>
        public static string ç {
            get {
                return ResourceManager.GetString("ç", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string ð {
            get {
                return ResourceManager.GetString("ð", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.
        /// </summary>
        public static string é {
            get {
                return ResourceManager.GetString("é", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.
        /// </summary>
        public static string è {
            get {
                return ResourceManager.GetString("è", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.
        /// </summary>
        public static string ê {
            get {
                return ResourceManager.GetString("ê", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.
        /// </summary>
        public static string ë {
            get {
                return ResourceManager.GetString("ë", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i.
        /// </summary>
        public static string í {
            get {
                return ResourceManager.GetString("í", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i.
        /// </summary>
        public static string ì {
            get {
                return ResourceManager.GetString("ì", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i.
        /// </summary>
        public static string î {
            get {
                return ResourceManager.GetString("î", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i.
        /// </summary>
        public static string ï {
            get {
                return ResourceManager.GetString("ï", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        public static string ñ {
            get {
                return ResourceManager.GetString("ñ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o.
        /// </summary>
        public static string ó {
            get {
                return ResourceManager.GetString("ó", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o.
        /// </summary>
        public static string ò {
            get {
                return ResourceManager.GetString("ò", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o.
        /// </summary>
        public static string ô {
            get {
                return ResourceManager.GetString("ô", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o.
        /// </summary>
        public static string ö {
            get {
                return ResourceManager.GetString("ö", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o.
        /// </summary>
        public static string õ {
            get {
                return ResourceManager.GetString("õ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o.
        /// </summary>
        public static string ø {
            get {
                return ResourceManager.GetString("ø", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p.
        /// </summary>
        public static string þ {
            get {
                return ResourceManager.GetString("þ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u.
        /// </summary>
        public static string ú {
            get {
                return ResourceManager.GetString("ú", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u.
        /// </summary>
        public static string ù {
            get {
                return ResourceManager.GetString("ù", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u.
        /// </summary>
        public static string û {
            get {
                return ResourceManager.GetString("û", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u.
        /// </summary>
        public static string ü {
            get {
                return ResourceManager.GetString("ü", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        public static string ý {
            get {
                return ResourceManager.GetString("ý", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        public static string ÿ {
            get {
                return ResourceManager.GetString("ÿ", resourceCulture);
            }
        }
    }
}
