//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Linq;

namespace StrixIT.Platform.Core.Tests
{
    [TestClass()]
    public class EntityTest
    {
        [TestMethod()]
        public void EntityWithoutPropertyRequirementsMustBeInvalid()
        {
            var entity = new TestEntity();
            bool result = entity.IsValid;
            Assert.IsFalse(result);
        }

        [TestMethod()]
        public void EntityWithPropertyRequirementsMetMustBeValid()
        {
            var entity = new TestEntity();
            entity.Name = "Test";
            entity.Number = 10;
            entity.Date = DateTime.Now;
            bool result = entity.IsValid;
            Assert.IsTrue(result);
        }

        [TestMethod()]
        public void EntityWithCustomValidationRulesNotMetMustBeInvalid()
        {
            CustomValidateEntity entity = new CustomValidateEntity();
            entity.Number = 1;
            entity.Name = "Just another entity";
            bool result = entity.IsValid;
            Assert.IsFalse(result);
        }

        [TestMethod()]
        public void EntityWithPropertyRequirementsNotMetButCustomValidationRulesMetMustBeInvalid()
        {
            CustomValidateEntity entity = new CustomValidateEntity();
            entity.Name = "TestEntity";
            bool result = entity.IsValid;
            Assert.IsFalse(result);
        }

        [TestMethod()]
        public void EntityWithCustomValidationRulesMetMustBeValid()
        {
            CustomValidateEntity entity = new CustomValidateEntity();
            entity.Number = 1;
            entity.Name = "TestEntity";
            bool result = entity.IsValid;
            Assert.IsTrue(result);
        }
    }
}
