//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace StrixIT.Platform.Core.Tests
{
    public class TestCustomField : CustomField
    {
        public Guid GroupId { get; set; }
    }
}
