//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;

namespace StrixIT.Platform.Core.Tests
{
    [TestClass()]
    public class ValidationTest
    {
        #region Public Methods

        [TestMethod()]
        public void EntityWithoutPropertyRequirementsMustBeInvalid()
        {
            var entity = new TestEntity();
            bool result = entity.Validate();
            Assert.IsFalse(result);
        }

        [TestMethod()]
        public void EntityWithPropertyRequirementsMetMustBeValid()
        {
            var entity = new TestEntity();
            entity.Name = "Test";
            entity.Number = 10;
            entity.Date = DateTime.Now;
            bool result = entity.Validate();
            Assert.IsTrue(result);
        }

        #endregion Public Methods
    }
}