//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.VisualStudio.TestTools.UnitTesting;
using StrixIT.Platform.Core;
using StrixIT.Platform.Core.DependencyInjection;
using System.Linq;

namespace StrixIT.Platform.Framework.Tests
{
    [TestClass]
    public class DependencyInjectorTests
    {
        #region Public Methods

        [TestMethod]
        public void GetTypeListShouldReturnAllTypesBasedOnRequestedType()
        {
            var result = DependencyInjector.GetTypeList(typeof(IServiceConfiguration));
            Assert.IsTrue(result.Any(r => r == typeof(PlatformServiceConfiguration)));
            Assert.AreEqual(2, result.Count);
        }

        #endregion Public Methods
    }
}