//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using StrixIT.Platform.Core;

namespace StrixIT.Platform.Framework.Tests
{
    public class TestEntityViewModel
    {
        #region Public Properties

        public string Description { get; set; }
        public int Id { get; set; }

        public string Name { get; set; }
        public string NotAvailable { get; set; }

        [StrixRequired]
        public long Number { get; set; }

        #endregion Public Properties
    }
}