//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace StrixIT.Platform.Core.Tests
{
    public class IntEntityViewModel
    {
        public int Id { get; set; }
        public string EntityName { get; set; }
        public int Order { get; set; }
        public bool Required { get; set; }
        public DateTime? Date { get; set; }
        public string ViewModelOnly { get; set; }
    }
}